/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hw7;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.StoredProcedureQuery;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author Ashraf Habromman
 */
public class MainInterFace extends javax.swing.JFrame {

    /**
     * Creates new form MainInterFace
     */
    public MainInterFace() {
        initComponents();
        String [] ageGroupList = {"All","Less than 10", "11-20", "21-30","31-40", "41-50", "Greater than 51"};
        DefaultComboBoxModel list = new DefaultComboBoxModel(ageGroupList);
        this.jCBoxAgeGroup.setModel(list);
        this.jCBoxAgeGroup.setSelectedIndex(-1);
        
        this.jTextName.setEditable(false);
        this.jTextAge.setEditable(false);
        this.jTextCovid19.setEditable(false);
        this.jTextAge.setText("Not Editable");
        this.jTextCovid19.setText("Not Ed");    
        this.jTextName.setText("Not Editable");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextAge = new javax.swing.JTextField();
        jTextCovid19 = new javax.swing.JTextField();
        jTextName = new javax.swing.JTextField();
        jBtnGetData = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jCBoxAgeGroup = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtSsn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Hotel Data About covid 19 ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 0, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-coronavirus-100.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Hotel Data about covid 19 ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Name ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Covid 19 ? Enter 1 or 0 ");

        jTextAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAgeActionPerformed(evt);
            }
        });

        jTextCovid19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCovid19ActionPerformed(evt);
            }
        });

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jBtnGetData.setText("Get data by Ssn ");
        jBtnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGetDataActionPerformed(evt);
            }
        });

        jButton2.setText(" Make a report ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Chose the age group ");

        jCBoxAgeGroup.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCBoxAgeGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBoxAgeGroup.setToolTipText("");
        jCBoxAgeGroup.setName(""); // NOI18N
        jCBoxAgeGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxAgeGroupActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Make a report based-on age group that you chose  :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Ssn");

        jTxtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSsnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Get data by entering ssn ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBoxAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(jTextCovid19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnGetData, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addGap(20, 20, 20))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jBtnGetData))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCovid19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBoxAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAgeActionPerformed

    private void jTextCovid19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCovid19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCovid19ActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jBtnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGetDataActionPerformed
        try {
            // TODO add your handling code here:
  
//            OracleDataSource ods = new  OracleDataSource();
//            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
//            ods.setUser("ashraf");
//            ods.setPassword("123456");
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("HW7ProcedurePU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();
            //using jpa 
            System.out.print("qwertygfdds");
            StoredProcedureQuery getBySsn = em.createNamedStoredProcedureQuery("HotelGuest.GET_DATA_BY_SSN");
            System.out.print("qwertygfdds");
            getBySsn.setParameter("GUEST_SSN_IN", Integer.parseInt(this.jTxtSsn.getText()));
            
            getBySsn.execute();
            
            String guestName = (String) getBySsn.getOutputParameterValue(2);
            Long age =(Long) getBySsn.getOutputParameterValue(3);
            
            String haveCovid19 = (String) getBySsn.getOutputParameterValue(4);
            
            this.jTextName.setText(guestName);
            this.jTextAge.setText(age+"");
            this.jTextCovid19.setText(haveCovid19);
            
            
           
            //em.persist(hg);
            //em.getTransaction().begin();
            em.getTransaction().commit();
            em.close();
            emf.close();
//            
//            this.jTextAge.setText("");
//            this.jTextCovid19.setText("");
//            this.jTextName.setText("");
//           
//                        Connection conn =ods.getConnection();
//            
//            Integer ssn = Integer.parseInt(this.jTxtSsn.getText());
//            //using jpa 
//            System.out.println("qwertygfdds");
//            CallableStatement callProsedure = conn.prepareCall("{call GET_DATA_BY_SSN(?,?,?,?)}");
//            System.out.println("qwertygfdds");
//            callProsedure.setObject(1, (Integer)ssn);   
//            callProsedure.registerOutParameter(2, Types.VARCHAR);
//            callProsedure.registerOutParameter(3, Types.NUMERIC);
//            callProsedure.registerOutParameter(4, Types.VARCHAR);
//             System.out.println("qwertygfdds");
//            String guestName = (String) callProsedure.getString(1);
//             System.out.println("qwertygfdds");
//            BigInteger age =(BigInteger) callProsedure.getObject(2);
//             System.out.println("qwertygfdds");
//            String haveCovid19 = (String) callProsedure.getString(3);
//            
//            
//            
            
            
            
       
        } catch (Exception ex) {
           // Logger.getLogger(MainInterFace.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,"Maybe data base don't have any guest with this ssn");
            System.out.print(ex.toString());

        }
        
        
    }//GEN-LAST:event_jBtnGetDataActionPerformed

    private void jCBoxAgeGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxAgeGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxAgeGroupActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        OracleDataSource ods;
        try {
            
            if(this.jCBoxAgeGroup.getSelectedIndex() != -1){
                ods = new OracleDataSource();
             ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
             ods.setUser("ashraf");
             ods.setPassword("123456");
             Connection conn = ods.getConnection();
             InputStream input = new FileInputStream(new File("covid.jrxml"));
             JasperDesign jsDes = JRXmlLoader.load(input);
             JasperReport jasRep = JasperCompileManager.compileReport(jsDes);
             HashMap paramerter = new HashMap<String, BigInteger>();
             String fileName = "" ;
             
             if(this.jCBoxAgeGroup.getSelectedIndex()==0){
                 paramerter.put("ageFrom", 0);
                 paramerter.put("ageTo", 1000);
                 fileName = "ReportAboutCovid19ForAllAges";
             }
            else if(this.jCBoxAgeGroup.getSelectedIndex()==1){
                 paramerter.put("ageFrom", 0);
                 paramerter.put("ageTo", 10);
                 fileName = "ReportAboutCovid19ForAgeGroupLessThan10";
             }
             else if(this.jCBoxAgeGroup.getSelectedIndex()==2){
                 paramerter.put("ageFrom", 11);
                 paramerter.put("ageTo", 20);
                 fileName = "ReportAboutCovid19ForAgeGroupBetween11and20";
             }
             else if(this.jCBoxAgeGroup.getSelectedIndex()==3){
                 paramerter.put("ageFrom", 21);
                 paramerter.put("ageTo", 30);
                 fileName = "ReportAboutCovid19ForAgeGroupBetween21and30";
             }
             else if(this.jCBoxAgeGroup.getSelectedIndex()==4){
                 paramerter.put("ageFrom", 31);
                 paramerter.put("ageTo", 40);
                 fileName = "ReportAboutCovid19ForAgeGroupBetween31and40";
             }
             else if(this.jCBoxAgeGroup.getSelectedIndex()==5){
                 paramerter.put("ageFrom", 41);
                 paramerter.put("ageTo", 50);
                 fileName = "ReportAboutCovid19ForAgeGroupBetween41and50";
             }
             else if(this.jCBoxAgeGroup.getSelectedIndex()==6){
                 paramerter.put("ageFrom", 51);
                 paramerter.put("ageTo", 1000);
                  fileName = "ReportAboutCovid19ForAgeGroupGreaterThan51";
             }
             
             JasperPrint jasPrt = JasperFillManager.fillReport(jasRep, paramerter, conn);
             OutputStream output = new FileOutputStream(new File(fileName+".pdf"));
             JasperExportManager.exportReportToPdfStream(jasPrt, output);
             input.close();
             output.close();
             conn.close();
            }
            else JOptionPane.showMessageDialog(rootPane, "Please select the Age group to make the file you want.");
            
        } catch (Exception ex) {
         
            JOptionPane.showMessageDialog(rootPane, ex.toString());
            //  Logger.getLogger(MainInterFace.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSsnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new MainInterFace().setVisible(true);
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGetData;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCBoxAgeGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextCovid19;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTxtSsn;
    // End of variables declaration//GEN-END:variables
}
